# Generated by Django 3.2.7 on 2021-12-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectToHeal', '0002_auto_20211212_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
