# Generated by Django 3.2.7 on 2021-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectToHeal', '0003_rename_blogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='blogCovers'),
        ),
    ]
