# Generated by Django 3.2.7 on 2021-12-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectToHeal', '0005_blog_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(default=''),
        ),
    ]
